server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      client-type: lettuce
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-exp: 3600000
  refresh-exp: 1209600000
  header: Authorization
  prefix: Bearer